pipeline {
  agent any
  stages {

    stage("Clean Up") {
      steps {
        deleteDir()
      }
    }
    stage("Clone Repo") {
      steps {
        bat "git clone https://github.com/GH94GitHub/PhotoViewage.git"
      }
    }
    stage("Build") {
      steps {
        bat "ng build"
      }
    }
    stage("Deploy") {
      steps {
        bat "ng serve -o"
      }
    }
    stage("Done") {
      steps {
        echo "Done"
      }
    }
  }
}
