pipeline {
  agent any
  stages {
    stage("Clean Up") {
      steps {
        deleteDir()
      }
    }
    stage("Clone Repo") {
      steps {
        bat "git clone https://github.com/GH94GitHub/PhotoViewage.git"
      }
    }
    stage("Install NPM Packages") {
      steps {
        dir("PhotoViewage") {
          bat "npm i"
        }
      }
    }
    stage("Build") {
      steps {
        dir("PhotoViewage") {
          bat "ng build"
        }
      }
    }
    stage("Deploy") {
      steps {
        dir("PhotoViewage/dist/photoviewage") {
          bat "aws s3 rm s3://photoviewage --recursive"
          bat "aws s3 sync . s3://photoviewage"
        }
      }
    }
    stage("End Clean Up") {
      steps {
        deleteDir()
      }
    }
  }
}
